### ISSUE TITLE
Fix Documentation structure under surveilr.com/docs

### ISSUE THREAD

**Issue by geovlazar** [surveilr/www.surveilr.com#52]
1. The content/docs is incorrect, it should be content/docs/en for English content
2. There should be no docs/docs, all subdirectories should be under content/docs/<language> like content/docs/en
3. For now, unless we have other languages we can remove them so that they do not have "junk" content
4. Why is there a surveilr under docs?

![image](https://github.com/user-attachments/assets/34e9cc7d-d1f8-475e-8235-0588c1d83a74)

**Comment by AjayKuruvath** [comment]
https://www.surveilr.com/docs/core/getting-started/

If we want "docs" to appear in the URL, we need to create a "docs" folder inside src/content/docs. However, if we don't want "docs" in the URL, we can remove the "docs" folder from src/content/docs.

Since our "docs" section uses Starlight, it treats src/content/docs as the root. Therefore, to include "docs" in the URL, we need to create a "docs" folder within src/content/docs.

**Comment by ajaykumaran** [comment]
@pradeepcdlm, the folder structure has been updated according to the layout provided by @shah. Please verify and close the ticket.

**Comment by pradeepcdlm** [comment]
Thanks @ajaykumaran  for the update, let me check and will take the next steps.

**Comment by pradeepcdlm** [comment]
@ajaykumaran, following the discussion with Shahid on 10/08/2024, we need to consult with the Astro team via the Discord channel to identify the best solution for managing documents in Starlight. Once we finalize the proper structure, we can proceed to close this ticket.

cc  @geovlazar , @AjayKuruvath

**Comment by AjayKuruvath** [comment]
We removed one redundant "docs" folder in src/content/docs so that there is only one folder, and "docs" will now be included in the URL. We also added a slug field to every markdown page's frontmatter, and soon after that, the URLs will follow what the value prescribed in the slug. We updated all pages accordingly.

![Screenshot from 2024-10-09 14-13-46](https://github.com/user-attachments/assets/66a72fc7-4e78-42e0-bdbc-f2823a65a4ea)

**Comment by temiye18** [comment]
> @ajaykumaran, following the discussion with Shahid on 10/08/2024, we need to consult with the Astro team via the Discord channel to identify the best solution for managing documents in Starlight. Once we finalize the proper structure, we can proceed to close this ticket.
> 
> cc @geovlazar , @AjayKuruvath

I have consulted with the Astro team via their GitHub help desk and the recommended solution is to have a nested `docs` folder within the root `docs` [#2447 ](https://github.com/withastro/starlight/discussions/2447#discussioncomment-10881043)  pending the time they implement a feature that allows a `base` property to be specified within the starlight config object ( [here](https://github.com/withastro/starlight/discussions/966) )

**Comment by temiye18** [comment]
> We removed one redundant "docs" folder in src/content/docs so that there is only one folder, and "docs" will now be included in the URL. We also added a slug field to every markdown page's frontmatter, and soon after that, the URLs will follow what the value prescribed in the slug. We updated all pages accordingly.
> 
> ![Screenshot from 2024-10-09 14-13-46](https://private-user-images.githubusercontent.com/121004161/374879558-66a72fc7-4e78-42e0-bdbc-f2823a65a4ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1NDIwMTQsIm5iZiI6MTcyODU0MTcxNCwicGF0aCI6Ii8xMjEwMDQxNjEvMzc0ODc5NTU4LTY2YTcyZmM3LTRlNzgtNDJlMC1iZGJjLWYyODIzYTY1YTRlYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMFQwNjI4MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NmIzZDNjOTcyNTg1Y2I4ZjVlZjk1MWIxYTEwNmZhMDNhMWRjMTczNjM3YjNjN2RjYmU2MDAwZjNkYzY2OWQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.NtHUurWNDDXTP_Bh4riuisPNpk6nVEUAD8LPuD-nUJQ)

@AjayKuruvath  the Astro stream mentioned this solution is not a good approach at scale which makes a lot of sense because the chances of errors being introduced by developers are on the high side. I have implemented the recommended approach by the Astro team as seen [here](https://github.com/withastro/starlight/discussions/2447#discussioncomment-10881043)
